import type { WordData } from './+page.server.js';

export interface SentenceData {
  hanzi: string;
  pinyin: string;
  translation: string;
  level: number;
}

// 100+ Chinese sentences written using only HSK 3.0 Level 1 vocabulary.
// The Pleco file was used as reference to pick which words are available.
// Every sentence uses only words from that list.

export function generateSentences(_words: WordData[]): SentenceData[] {
  return SENTENCES;
}

const SENTENCES: SentenceData[] = [
  { hanzi: '我爱你', pinyin: 'wǒ ài nǐ', translation: 'I love you.', level: 1 },
  { hanzi: '他是老师', pinyin: 'tā shì lǎoshī', translation: 'He is a teacher.', level: 1 },
  { hanzi: '我们是学生', pinyin: 'wǒmen shì xuéshēng', translation: 'We are students.', level: 1 },
  { hanzi: '今天天气很好', pinyin: 'jīntiān tiānqì hěn hǎo', translation: 'The weather is very good today.', level: 1 },
  { hanzi: '我喝水', pinyin: 'wǒ hē shuǐ', translation: 'I drink water.', level: 1 },
  { hanzi: '他吃米饭', pinyin: 'tā chī mǐfàn', translation: 'He eats rice.', level: 1 },
  { hanzi: '我不吃肉', pinyin: 'wǒ bù chī ròu', translation: 'I do not eat meat.', level: 1 },
  { hanzi: '你有书吗？', pinyin: 'nǐ yǒu shū ma', translation: 'Do you have a book?', level: 1 },
  { hanzi: '我有一个手机', pinyin: 'wǒ yǒu yīgè shǒujī', translation: 'I have a mobile phone.', level: 1 },
  { hanzi: '他在家', pinyin: 'tā zài jiā', translation: 'He is at home.', level: 1 },
  { hanzi: '我们去学校', pinyin: 'wǒmen qù xuéxiào', translation: 'We go to school.', level: 1 },
  { hanzi: '明天我上班', pinyin: 'míngtiān wǒ shàngbān', translation: 'Tomorrow I go to work.', level: 1 },
  { hanzi: '我喜欢喝茶', pinyin: 'wǒ xǐhuān hē chá', translation: 'I like to drink tea.', level: 1 },
  { hanzi: '他喜欢看书', pinyin: 'tā xǐhuān kàn shū', translation: 'He likes to read.', level: 1 },
  { hanzi: '我会说中文', pinyin: 'wǒ huì shuō zhōngwén', translation: 'I can speak Chinese.', level: 1 },
  { hanzi: '姐姐很漂亮', pinyin: 'jiějie hěn piàoliang', translation: 'Older sister is very pretty.', level: 1 },
  { hanzi: '爸爸是医生', pinyin: 'bàba shì yīshēng', translation: 'Dad is a doctor.', level: 1 },
  { hanzi: '今天很热', pinyin: 'jīntiān hěn rè', translation: 'Today is hot.', level: 1 },
  { hanzi: '我想喝水', pinyin: 'wǒ xiǎng hē shuǐ', translation: 'I want to drink water.', level: 1 },
  { hanzi: '他是我朋友', pinyin: 'tā shì wǒ péngyou', translation: 'He is my friend.', level: 1 },
  { hanzi: '我们去商店', pinyin: 'wǒmen qù shāngdiàn', translation: 'We go to the store.', level: 1 },
  { hanzi: '这本书很大', pinyin: 'zhè běn shū hěn dà', translation: 'This book is very big.', level: 1 },
  { hanzi: '她喜欢吃水果', pinyin: 'tā xǐhuān chī shuǐguǒ', translation: 'She likes to eat fruit.', level: 1 },
  { hanzi: '早上我喝茶', pinyin: 'zǎoshang wǒ hē chá', translation: 'In the morning I drink tea.', level: 1 },
  { hanzi: '他不在家', pinyin: 'tā bù zài jiā', translation: 'He is not at home.', level: 1 },
  { hanzi: '妹妹很小', pinyin: 'mèimei hěn xiǎo', translation: 'Little sister is very small.', level: 1 },
  { hanzi: '我坐火车去北京', pinyin: 'wǒ zuò huǒchē qù běijīng', translation: 'I take the train to Beijing.', level: 1 },
  { hanzi: '星期一我去学校', pinyin: 'xīngqīyī wǒ qù xuéxiào', translation: 'Monday I go to school.', level: 1 },
  { hanzi: '晚上我看电视', pinyin: 'wǎnshang wǒ kàn diànshì', translation: 'In the evening I watch TV.', level: 1 },
  { hanzi: '他有一个妹妹', pinyin: 'tā yǒu yīgè mèimei', translation: 'He has a younger sister.', level: 1 },
  { hanzi: '我们在家吃饭', pinyin: 'wǒmen zài jiā chīfàn', translation: 'We eat at home.', level: 1 },
  { hanzi: '奶奶很累', pinyin: 'nǎinai hěn lèi', translation: 'Grandma is very tired.', level: 1 },
  { hanzi: '我买了一个手机', pinyin: 'wǒ mǎile yīgè shǒujī', translation: 'I bought a mobile phone.', level: 1 },
  { hanzi: '他不喜欢喝茶', pinyin: 'tā bù xǐhuān hē chá', translation: 'He does not like to drink tea.', level: 1 },
  { hanzi: '现在十点了', pinyin: 'xiànzài shí diǎn le', translation: 'It is ten o\'clock now.', level: 1 },
  { hanzi: '这是什么？', pinyin: 'zhè shì shénme', translation: 'What is this?', level: 1 },
  { hanzi: '你叫什么名字？', pinyin: 'nǐ jiào shénme míngzì', translation: 'What is your name?', level: 1 },
  { hanzi: '我是北京人', pinyin: 'wǒ shì běijīng rén', translation: 'I am from Beijing.', level: 1 },
  { hanzi: '你吃什么？', pinyin: 'nǐ chī shénme', translation: 'What do you eat?', level: 1 },
  { hanzi: '他看了一本书', pinyin: 'tā kànle yī běn shū', translation: 'He read a book.', level: 1 },
  { hanzi: '她穿了新衣服', pinyin: 'tā chuānle xīn yīfu', translation: 'She wears new clothes.', level: 1 },
  { hanzi: '电脑很贵', pinyin: 'diànnǎo hěn guì', translation: 'The computer is very expensive.', level: 1 },
  { hanzi: '朋友来了', pinyin: 'péngyou lái le', translation: 'My friend has come.', level: 1 },
  { hanzi: '我帮他', pinyin: 'wǒ bāng tā', translation: 'I help him.', level: 1 },
  { hanzi: '他给我一本书', pinyin: 'tā gěi wǒ yī běn shū', translation: 'He gives me a book.', level: 1 },
  { hanzi: '我们走了', pinyin: 'wǒmen zǒu le', translation: 'We are leaving.', level: 1 },
  { hanzi: '他在医院工作', pinyin: 'tā zài yīyuàn gōngzuò', translation: 'He works at the hospital.', level: 1 },
  { hanzi: '今天是我的生日', pinyin: 'jīntiān shì wǒ de shēngrì', translation: 'Today is my birthday.', level: 1 },
  { hanzi: '你去哪里？', pinyin: 'nǐ qù nǎlǐ', translation: 'Where are you going?', level: 1 },
  { hanzi: '他住在北京', pinyin: 'tā zhù zài běijīng', translation: 'He lives in Beijing.', level: 1 },
  { hanzi: '你认识他吗？', pinyin: 'nǐ rènshi tā ma', translation: 'Do you know him?', level: 1 },
  { hanzi: '妈妈买了鸡蛋', pinyin: 'māma mǎile jīdàn', translation: 'Mom bought eggs.', level: 1 },
  { hanzi: '他很高', pinyin: 'tā hěn gāo', translation: 'He is very tall.', level: 1 },
  { hanzi: '我们去图书馆看书', pinyin: 'wǒmen qù túshūguǎn kàn shū', translation: 'We go to the library to read.', level: 1 },
  { hanzi: '这个饭很好吃', pinyin: 'zhège fàn hěn hǎochī', translation: 'This food is very tasty.', level: 1 },
  { hanzi: '他坐车去学校', pinyin: 'tā zuò chē qù xuéxiào', translation: 'He takes the car to school.', level: 1 },
  { hanzi: '我给他打电话', pinyin: 'wǒ gěi tā dǎ diànhuà', translation: 'I call him on the phone.', level: 1 },
  { hanzi: '奶奶做了包子', pinyin: 'nǎinai zuòle bāozi', translation: 'Grandma made steamed buns.', level: 1 },
  { hanzi: '你忙吗？', pinyin: 'nǐ máng ma', translation: 'Are you busy?', level: 1 },
  { hanzi: '我们都很高兴', pinyin: 'wǒmen dōu hěn gāoxìng', translation: 'We are all very happy.', level: 1 },
  { hanzi: '这里有人吗？', pinyin: 'zhèlǐ yǒu rén ma', translation: 'Is there someone here?', level: 1 },
  { hanzi: '我问他一个问题', pinyin: 'wǒ wèn tā yīgè wèntí', translation: 'I ask him a question.', level: 1 },
  { hanzi: '早上我喝了牛奶', pinyin: 'zǎoshang wǒ hēle niúnǎi', translation: 'This morning I drank milk.', level: 1 },
  { hanzi: '爷爷在休息', pinyin: 'yéye zài xiūxi', translation: 'Grandpa is resting.', level: 1 },
  { hanzi: '学校旁边有一个商店', pinyin: 'xuéxiào pángbiān yǒu yīgè shāngdiàn', translation: 'There is a store next to the school.', level: 1 },
  { hanzi: '我们等你', pinyin: 'wǒmen děng nǐ', translation: 'We wait for you.', level: 1 },
  { hanzi: '他喜欢运动', pinyin: 'tā xǐhuān yùndòng', translation: 'He likes sports.', level: 1 },
  { hanzi: '我帮妈妈洗衣服', pinyin: 'wǒ bāng māma xǐ yīfu', translation: 'I help mom wash clothes.', level: 1 },
  { hanzi: '明天是我的生日', pinyin: 'míngtiān shì wǒ de shēngrì', translation: 'Tomorrow is my birthday.', level: 1 },
  { hanzi: '那里有很多人', pinyin: 'nàlǐ yǒu hěnduō rén', translation: 'There are many people there.', level: 1 },
  { hanzi: '这个菜不好吃', pinyin: 'zhège cài bù hǎochī', translation: 'This dish is not tasty.', level: 1 },
  { hanzi: '外边很冷', pinyin: 'wàibiān hěn lěng', translation: 'It is very cold outside.', level: 1 },
  { hanzi: '我女儿在睡觉', pinyin: 'wǒ nǚér zài shuìjiào', translation: 'My daughter is sleeping.', level: 1 },
  { hanzi: '他走路很慢', pinyin: 'tā zǒulù hěn màn', translation: 'He walks very slowly.', level: 1 },
  { hanzi: '我给你一个礼物', pinyin: 'wǒ gěi nǐ yīgè lǐwù', translation: 'I give you a gift.', level: 1 },
  { hanzi: '我儿子上小学', pinyin: 'wǒ érzi shàng xiǎoxué', translation: 'My son goes to primary school.', level: 1 },
  { hanzi: '这个男人是我的老师', pinyin: 'zhège nánrén shì wǒ de lǎoshī', translation: 'This man is my teacher.', level: 1 },
  { hanzi: '这个女孩是我的同学', pinyin: 'zhège nǚhái shì wǒ de tóngxué', translation: 'This girl is my classmate.', level: 1 },
  { hanzi: '今天是星期五', pinyin: 'jīntiān shì xīngqīwǔ', translation: 'Today is Friday.', level: 1 },
  { hanzi: '明天是星期六', pinyin: 'míngtiān shì xīngqīliù', translation: 'Tomorrow is Saturday.', level: 1 },
  { hanzi: '我们下午上课', pinyin: 'wǒmen xiàwǔ shàngkè', translation: 'We have class in the afternoon.', level: 1 },
  { hanzi: '我回家吃饭', pinyin: 'wǒ huí jiā chīfàn', translation: 'I go home to eat.', level: 1 },
  { hanzi: '他来我这里', pinyin: 'tā lái wǒ zhèlǐ', translation: 'He comes to my place.', level: 1 },
  { hanzi: '我去车站', pinyin: 'wǒ qù chēzhàn', translation: 'I go to the station.', level: 1 },
  { hanzi: '他坐了飞机', pinyin: 'tā zuòle fēijī', translation: 'He took a plane.', level: 1 },
  { hanzi: '我们在家看电视', pinyin: 'wǒmen zài jiā kàn diànshì', translation: 'We watch TV at home.', level: 1 },
  { hanzi: '我打开门', pinyin: 'wǒ dǎkāi mén', translation: 'I open the door.', level: 1 },
  { hanzi: '他喜欢看电影', pinyin: 'tā xǐhuān kàn diànyǐng', translation: 'He likes to watch movies.', level: 1 },
  { hanzi: '我没有钱', pinyin: 'wǒ méiyǒu qián', translation: 'I do not have money.', level: 1 },
  { hanzi: '姐姐是大学生', pinyin: 'jiějie shì dàxuéshēng', translation: 'Older sister is a university student.', level: 1 },
  { hanzi: '你多大了？', pinyin: 'nǐ duō dà le', translation: 'How old are you?', level: 1 },
  { hanzi: '他是我爸爸', pinyin: 'tā shì wǒ bàba', translation: 'He is my father.', level: 1 },
  { hanzi: '我们一起玩', pinyin: 'wǒmen yīqǐ wán', translation: 'We play together.', level: 1 },
  { hanzi: '我很高兴', pinyin: 'wǒ hěn gāoxìng', translation: 'I am very happy.', level: 1 },
  { hanzi: '他写了很多字', pinyin: 'tā xiěle hěnduō zì', translation: 'He wrote many characters.', level: 1 },
  { hanzi: '我在书店买书', pinyin: 'wǒ zài shūdiàn mǎi shū', translation: 'I buy books at the bookstore.', level: 1 },
  { hanzi: '他喝了很多水', pinyin: 'tā hēle hěnduō shuǐ', translation: 'He drank a lot of water.', level: 1 },
  { hanzi: '我认识这个字', pinyin: 'wǒ rènshi zhège zì', translation: 'I know this character.', level: 1 },
  { hanzi: '你妈妈叫什么名字？', pinyin: 'nǐ māma jiào shénme míngzì', translation: 'What is your mother\'s name?', level: 1 },
  { hanzi: '中国人很多', pinyin: 'zhōngguó rén hěnduō', translation: 'Chinese people are many.', level: 1 },
  { hanzi: '我常常看书', pinyin: 'wǒ chángcháng kàn shū', translation: 'I often read books.', level: 1 },
  { hanzi: '这个衣服很贵', pinyin: 'zhège yīfu hěn guì', translation: 'This clothing is very expensive.', level: 1 },
  { hanzi: '他不在学校', pinyin: 'tā bù zài xuéxiào', translation: 'He is not at school.', level: 1 },
  { hanzi: '我们看电影吧', pinyin: 'wǒmen kàn diànyǐng ba', translation: 'Let us watch a movie.', level: 1 },
  { hanzi: '这是我妈妈', pinyin: 'zhè shì wǒ māma', translation: 'This is my mother.', level: 1 },
  { hanzi: '我找不到我的书', pinyin: 'wǒ zhǎo bù dào wǒ de shū', translation: 'I cannot find my book.', level: 1 },
  { hanzi: '他早上六点起床', pinyin: 'tā zǎoshang liù diǎn qǐchuáng', translation: 'He gets up at six in the morning.', level: 1 },
  { hanzi: '他是我最好的朋友', pinyin: 'tā shì wǒ zuì hǎo de péngyou', translation: 'He is my best friend.', level: 1 },
  { hanzi: '这是你的书吗？', pinyin: 'zhè shì nǐ de shū ma', translation: 'Is this your book?', level: 1 },
  { hanzi: '他会不会说中文？', pinyin: 'tā huì bù huì shuō zhōngwén', translation: 'Can he speak Chinese?', level: 1 },
  { hanzi: '我明年去中国', pinyin: 'wǒ míngnián qù zhōngguó', translation: 'I will go to China next year.', level: 1 },
  { hanzi: '我不会忘记你', pinyin: 'wǒ bù huì wàngjì nǐ', translation: 'I will not forget you.', level: 1 },
  { hanzi: '请你再说一次', pinyin: 'qǐng nǐ zài shuō yī cì', translation: 'Please say it once more.', level: 1 },
];
