CREATE TABLE IF NOT EXISTS "daily_activity" (
  "id" serial PRIMARY KEY NOT NULL,
  "slug" text NOT NULL,
  "category" text NOT NULL,
  "category_description" text DEFAULT '' NOT NULL,
  "name" text NOT NULL,
  "detail" text DEFAULT '' NOT NULL,
  "icon" text DEFAULT 'sparkles' NOT NULL,
  "enabled" boolean DEFAULT true NOT NULL,
  "sort_order" integer DEFAULT 0 NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "daily_activity_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
INSERT INTO "daily_activity" ("slug", "category", "category_description", "name", "detail", "icon", "sort_order") VALUES
  ('swim-10-laps', 'Movement', 'Get your body moving.', 'Swim 10 laps', 'Go to the pool and complete 10 easy laps.', 'waves', 10),
  ('run-2-km', 'Movement', 'Get your body moving.', 'Run 2 km', 'Run 2 km at a comfortable pace.', 'footprints', 20),
  ('do-20-squats', 'Movement', 'Get your body moving.', 'Do 20 squats', 'Complete 20 bodyweight squats.', 'dumbbell', 30),
  ('walk-20-minutes', 'Movement', 'Get your body moving.', 'Walk 20 minutes', 'Take a 20-minute walk outside.', 'leaf', 40),
  ('stretch-10-minutes', 'Movement', 'Get your body moving.', 'Stretch 10 minutes', 'Do 10 minutes of full-body stretching.', 'wind', 50),
  ('get-10-minutes-of-sunlight', 'Movement', 'Get your body moving.', 'Get 10 minutes of sunlight', 'Step outside and stay in morning or afternoon light for 10 minutes.', 'sun', 60),
  ('do-10-push-ups', 'Movement', 'Get your body moving.', 'Do 10 push-ups', 'Complete 10 push-ups, modified if needed.', 'dumbbell', 70),
  ('climb-5-flights-of-stairs', 'Movement', 'Get your body moving.', 'Climb 5 flights of stairs', 'Walk up 5 flights of stairs at a steady pace.', 'footprints', 80),
  ('draw-one-object', 'Creative', 'Make something with your hands or ideas.', 'Draw one object', 'Pick one object nearby and sketch it.', 'brush', 110),
  ('paint-one-small-piece', 'Creative', 'Make something with your hands or ideas.', 'Paint one small piece', 'Make one small painting or digital color study.', 'palette', 120),
  ('take-5-photos', 'Creative', 'Make something with your hands or ideas.', 'Take 5 photos', 'Capture 5 photos of interesting details around you.', 'camera', 130),
  ('write-5-journal-lines', 'Creative', 'Make something with your hands or ideas.', 'Write 5 journal lines', 'Write 5 lines about today or what is on your mind.', 'notebook-pen', 140),
  ('practice-one-song', 'Creative', 'Make something with your hands or ideas.', 'Practice one song', 'Sing or play through one song once.', 'music', 150),
  ('add-5-songs-to-a-playlist', 'Creative', 'Make something with your hands or ideas.', 'Add 5 songs to a playlist', 'Choose 5 songs for one playlist.', 'headphones', 160),
  ('write-one-short-poem', 'Creative', 'Make something with your hands or ideas.', 'Write one short poem', 'Write 4 to 8 lines about one image or feeling.', 'notebook-pen', 170),
  ('edit-one-photo', 'Creative', 'Make something with your hands or ideas.', 'Edit one photo', 'Choose one photo and make one finished edit.', 'camera', 180),
  ('read-10-pages', 'Learning', 'Feed your brain without overloading the day.', 'Read 10 pages', 'Read 10 pages from one book.', 'book-open', 210),
  ('watch-one-documentary-episode', 'Learning', 'Feed your brain without overloading the day.', 'Watch one documentary episode', 'Watch one episode or 20 minutes.', 'film', 220),
  ('review-15-vocabulary-words', 'Learning', 'Feed your brain without overloading the day.', 'Review 15 vocabulary words', 'Review 15 words from one language list.', 'message-circle', 230),
  ('solve-one-puzzle', 'Learning', 'Feed your brain without overloading the day.', 'Solve one puzzle', 'Finish one crossword, sudoku, or logic puzzle.', 'puzzle', 240),
  ('write-3-notes-on-one-topic', 'Learning', 'Feed your brain without overloading the day.', 'Write 3 notes on one topic', 'Pick one topic and write 3 useful notes.', 'sparkles', 250),
  ('watch-one-tutorial', 'Learning', 'Feed your brain without overloading the day.', 'Watch one tutorial', 'Watch one tutorial and write one takeaway.', 'film', 260),
  ('memorize-one-quote', 'Learning', 'Feed your brain without overloading the day.', 'Memorize one quote', 'Pick one short quote and repeat it until remembered.', 'book-open', 270),
  ('cook-one-meal', 'Home & Errands', 'Reset your space and handle life admin.', 'Cook one meal', 'Prepare one complete meal.', 'cooking-pot', 310),
  ('clear-your-desk', 'Home & Errands', 'Reset your space and handle life admin.', 'Clear your desk', 'Remove trash and put items back where they belong.', 'home', 320),
  ('fold-one-laundry-batch', 'Home & Errands', 'Reset your space and handle life admin.', 'Fold one laundry batch', 'Fold and put away one batch of clothes.', 'shirt', 330),
  ('buy-5-groceries', 'Home & Errands', 'Reset your space and handle life admin.', 'Buy 5 groceries', 'Buy 5 needed grocery items.', 'shopping-basket', 340),
  ('prep-2-meals', 'Home & Errands', 'Reset your space and handle life admin.', 'Prep 2 meals', 'Prepare ingredients or portions for 2 meals.', 'utensils', 350),
  ('water-all-plants', 'Home & Errands', 'Reset your space and handle life admin.', 'Water all plants', 'Check and water every plant that needs it.', 'sprout', 360),
  ('throw-away-10-things', 'Home & Errands', 'Reset your space and handle life admin.', 'Throw away 10 things', 'Find and discard 10 pieces of trash or clutter.', 'home', 370),
  ('wash-5-dishes', 'Home & Errands', 'Reset your space and handle life admin.', 'Wash 5 dishes', 'Wash 5 dishes or utensils from the sink.', 'utensils', 380),
  ('watch-one-movie', 'Relax & Play', 'Recover, enjoy, and make the day lighter.', 'Watch one movie', 'Pick one movie and finish it.', 'film', 410),
  ('play-30-minutes-of-a-game', 'Relax & Play', 'Recover, enjoy, and make the day lighter.', 'Play 30 minutes of a game', 'Set a timer and play for 30 minutes.', 'gamepad-2', 420),
  ('play-one-board-game-round', 'Relax & Play', 'Recover, enjoy, and make the day lighter.', 'Play one board game round', 'Finish one round of cards, dice, or a board game.', 'dice-5', 430),
  ('take-a-15-minute-coffee-break', 'Relax & Play', 'Recover, enjoy, and make the day lighter.', 'Take a 15-minute coffee break', 'Drink coffee or tea without multitasking.', 'coffee', 440),
  ('call-one-friend', 'Relax & Play', 'Recover, enjoy, and make the day lighter.', 'Call one friend', 'Call or voice note one friend.', 'heart-handshake', 450),
  ('listen-to-one-album', 'Relax & Play', 'Recover, enjoy, and make the day lighter.', 'Listen to one album', 'Play one album from start to finish.', 'headphones', 460),
  ('sit-quietly-for-10-minutes', 'Relax & Play', 'Recover, enjoy, and make the day lighter.', 'Sit quietly for 10 minutes', 'Sit without phone, music, or tasks for 10 minutes.', 'coffee', 470),
  ('send-one-kind-message', 'Relax & Play', 'Recover, enjoy, and make the day lighter.', 'Send one kind message', 'Send one sincere message to someone you appreciate.', 'heart-handshake', 480)
ON CONFLICT ("slug") DO UPDATE SET
  "category" = EXCLUDED."category",
  "category_description" = EXCLUDED."category_description",
  "name" = EXCLUDED."name",
  "detail" = EXCLUDED."detail",
  "icon" = EXCLUDED."icon",
  "sort_order" = EXCLUDED."sort_order",
  "enabled" = true,
  "updated_at" = now();
