INSERT INTO "daily_activity" (
  "slug",
  "category",
  "category_description",
  "name",
  "detail",
  "icon",
  "level",
  "sort_order"
) VALUES
  ('practice-one-song', 'Skill Practice', 'Improve a specific ability with one focused rep', 'Practice one guitar riff', 'Repeat one riff slowly', 'mic-vocal', 5, 610),
  ('mix-two-songs-once', 'Skill Practice', 'Improve a specific ability with one focused rep', 'Mix two songs once', 'Blend two tracks one time', 'audio-lines', 1, 620),
  ('tap-out-one-drum-pattern', 'Skill Practice', 'Improve a specific ability with one focused rep', 'Tap out a drum pattern', 'Make one short beat with your hands', 'drum', 1, 630),
  ('shadowbox-3-minutes', 'Skill Practice', 'Improve a specific ability with one focused rep', 'Shadowbox 3 minutes', 'Box the air for one short round', 'hand-fist', 1, 640),
  ('practice-one-boxing-combo', 'Skill Practice', 'Improve a specific ability with one focused rep', 'Practice one boxing combo', 'Repeat one simple combo slowly', 'biceps-flexed', 1, 650),
  ('practice-one-parking-drill', 'Skill Practice', 'Improve a specific ability with one focused rep', 'Practice one parking drill', 'Practice one safe parking maneuver', 'car-front', 1, 660),
  ('review-car-controls', 'Skill Practice', 'Improve a specific ability with one focused rep', 'Review car controls', 'Review pedals, mirrors, and signals', 'car', 1, 670),
  ('review-motorcycle-controls', 'Skill Practice', 'Improve a specific ability with one focused rep', 'Review motorcycle controls', 'Review throttle, brakes, and balance', 'gauge', 1, 680),
  ('send-one-check-in', 'Social', 'Keep relationships warm with one small action', 'Send one check-in', 'Ask one person how they are', 'mail-check', 2, 710),
  ('thank-one-person', 'Social', 'Keep relationships warm with one small action', 'Thank one person', 'Send one specific thank you', 'hand-heart', 2, 720),
  ('reply-to-one-message', 'Social', 'Keep relationships warm with one small action', 'Reply to one message', 'Answer one pending message', 'message-check', 2, 730),
  ('invite-someone-to-chat', 'Social', 'Keep relationships warm with one small action', 'Invite someone to chat', 'Ask one person for a short chat', 'users', 2, 740),
  ('drink-one-glass-of-water', 'Health', 'Support your body with one small care action', 'Drink one glass of water', 'Drink one full glass of water', 'glass-water', 3, 810),
  ('take-one-vitamin', 'Health', 'Support your body with one small care action', 'Take one vitamin', 'Take one planned supplement', 'pill', 2, 820),
  ('floss-your-teeth', 'Health', 'Support your body with one small care action', 'Floss your teeth', 'Floss once slowly', 'stethoscope', 2, 830),
  ('check-your-posture', 'Health', 'Support your body with one small care action', 'Check your posture', 'Reset your neck and shoulders', 'heart-pulse', 2, 840),
  ('set-a-sleep-time', 'Health', 'Support your body with one small care action', 'Set a sleep time', 'Choose tonight''s sleep time', 'clock-check', 2, 850),
  ('update-one-resume-line', 'Career', 'Move work and opportunities forward', 'Update one resume line', 'Improve one resume bullet', 'briefcase', 2, 910),
  ('review-one-portfolio-item', 'Career', 'Move work and opportunities forward', 'Review one portfolio item', 'Check one project for clarity', 'badge-check', 2, 920),
  ('practice-one-interview-answer', 'Career', 'Move work and opportunities forward', 'Practice one interview answer', 'Answer one prompt out loud', 'target', 2, 930),
  ('save-one-job-lead', 'Career', 'Move work and opportunities forward', 'Save one job lead', 'Save one role worth checking', 'briefcase-business', 2, 940)
ON CONFLICT ("slug") DO UPDATE SET
  "category" = EXCLUDED."category",
  "category_description" = EXCLUDED."category_description",
  "name" = EXCLUDED."name",
  "detail" = EXCLUDED."detail",
  "icon" = EXCLUDED."icon",
  "level" = EXCLUDED."level",
  "sort_order" = EXCLUDED."sort_order",
  "enabled" = true,
  "updated_at" = now();
