UPDATE "daily_activity"
SET "enabled" = false, "updated_at" = now();
--> statement-breakpoint
INSERT INTO "daily_activity" (
  "slug",
  "category",
  "category_description",
  "name",
  "detail",
  "icon",
  "level",
  "enabled",
  "sort_order"
) VALUES
  ('creative-making-block', 'Creative', 'Make or shape something worth keeping', 'Finish a creative piece', 'Take one creative thing from loose idea to a more complete artifact you would be willing to save, share, or revisit.', 'palette', 3, true, 110),
  ('creative-writing-block', 'Creative', 'Make or shape something worth keeping', 'Write with intention', 'Work on a journal entry, essay, poem, story, reflection, script, or long-form note until it feels meaningfully developed.', 'pen-line', 3, true, 120),
  ('creative-visual-block', 'Creative', 'Make or shape something worth keeping', 'Explore visual craft', 'Spend time with photography, drawing, painting, layout, collage, editing, or visual reference collection.', 'camera', 2, true, 130),
  ('creative-music-block', 'Creative', 'Make or shape something worth keeping', 'Spend time with music', 'Practice, listen closely, mix, record, arrange, or study music as an active creative session.', 'music', 3, true, 140),
  ('movement-outside-block', 'Movement', 'Use your body and change your state', 'Take an outdoor movement break', 'Go outside for low-pressure movement, fresh air, and a change of scenery without turning it into a workout.', 'footprints', 3, true, 210),
  ('movement-training-block', 'Movement', 'Use your body and change your state', 'Train your body', 'Do a focused strength, conditioning, boxing, mobility, or bodyweight session that feels like practice, not just a checkbox.', 'dumbbell', 3, true, 220),
  ('movement-water-cardio-block', 'Movement', 'Use your body and change your state', 'Do a cardio session', 'Choose swimming, running, cycling, dancing, or another sustained effort that raises your heart rate on purpose.', 'waves', 3, true, 230),
  ('movement-recovery-block', 'Movement', 'Use your body and change your state', 'Do mobility maintenance', 'Stretch, walk gently, do mobility drills, or release stiffness with light physical work. Keep this about the body, not mental rest.', 'wind', 3, true, 240),
  ('learning-reading-block', 'Learning', 'Feed your mind with focused attention', 'Read deeply', 'Spend focused time with a book, article, saved note, or essay and leave with something you can explain or reuse.', 'book-open', 3, true, 310),
  ('learning-study-block', 'Learning', 'Feed your mind with focused attention', 'Study something deliberately', 'Pick one topic and work through notes, tutorials, examples, vocabulary, exercises, or explanations until it becomes clearer.', 'brain', 3, true, 320),
  ('learning-language-block', 'Learning', 'Feed your mind with focused attention', 'Practice language', 'Review, speak, listen, write, translate, or memorize in a language you want to keep alive.', 'languages', 3, true, 330),
  ('learning-curiosity-block', 'Learning', 'Feed your mind with focused attention', 'Follow a curiosity thread', 'Research something you keep wondering about and collect the useful parts instead of drifting through random content.', 'newspaper', 2, true, 340),
  ('learning-capture-block', 'Learning', 'Feed your mind with focused attention', 'Capture what you learned', 'Turn recent reading, work, mistakes, or experience into notes, principles, examples, or reminders you can reuse.', 'notebook-text', 2, true, 350),
  ('career-asset-block', 'Career', 'Move your future work options forward', 'Improve a career asset', 'Work on a resume, portfolio, case study, project writeup, LinkedIn section, personal site, or proof of skill.', 'briefcase', 3, true, 410),
  ('career-search-block', 'Career', 'Move your future work options forward', 'Move the job search forward', 'Research roles, save leads, tailor an application, send a message, or make one concrete move toward an opportunity.', 'briefcase-business', 3, true, 420),
  ('career-interview-block', 'Career', 'Move your future work options forward', 'Practice for interviews', 'Practice product, behavioral, technical, case, or storytelling answers out loud and tighten the parts that felt weak.', 'target', 2, true, 430),
  ('career-network-block', 'Career', 'Move your future work options forward', 'Build professional connection', 'Reach out, follow up, ask for a conversation, share work, or strengthen a relationship tied to your future work.', 'heart-handshake', 2, true, 440),
  ('career-deep-focus-block', 'Career', 'Move your future work options forward', 'Move a work problem forward', 'Protect a focused session for one demanding professional problem, decision, analysis, product task, or coding task tied to work outcomes.', 'timer', 3, true, 450),
  ('career-personal-project-block', 'Career', 'Move your future work options forward', 'Build proof of skill', 'Move a portfolio, case study, public project, or demonstrable skill artifact forward so it strengthens future work options.', 'hammer', 2, true, 460),
  ('life-space-reset-block', 'Life Admin', 'Make your environment and obligations lighter', 'Reset your space', 'Make your room, desk, laundry, kitchen, or belongings noticeably easier to live with.', 'home', 3, true, 510),
  ('life-admin-block', 'Life Admin', 'Make your environment and obligations lighter', 'Handle life admin', 'Deal with bills, calendar, errands, forms, appointments, purchases, planning, or the unresolved practical things.', 'receipt', 3, true, 520),
  ('life-digital-reset-block', 'Life Admin', 'Make your environment and obligations lighter', 'Organize digital life', 'Clean up files, tabs, photos, notes, backups, inboxes, saved links, or anything digital that has become noisy.', 'folder-open', 3, true, 530),
  ('life-food-care-block', 'Life Admin', 'Make your environment and obligations lighter', 'Handle food logistics', 'Buy groceries, cook, meal prep, plan meals, clean the kitchen, or make eating practical and easier to manage.', 'cooking-pot', 3, true, 540),
  ('life-money-review-block', 'Life Admin', 'Make your environment and obligations lighter', 'Review your money', 'Check spending, bills, savings, subscriptions, investments, or budget decisions so your money situation feels less vague.', 'gauge', 2, true, 550),
  ('life-future-prep-block', 'Life Admin', 'Make your environment and obligations lighter', 'Stage tomorrow''s logistics', 'Set up clothes, bag, files, calendar, workspace, transport, or materials that reduce tomorrow''s practical friction.', 'bookmark', 2, true, 560),
  ('social-quality-time-block', 'Social', 'Spend attention on people, not just messages', 'Spend quality time with someone', 'Call, meet, chat, play, eat, or sit with someone where the main point is shared presence.', 'users', 3, true, 610),
  ('social-message-block', 'Social', 'Spend attention on people, not just messages', 'Catch up with people', 'Reply, check in, thank someone, invite someone, or clear the relationship messages you have been carrying around.', 'message-check', 3, true, 620),
  ('social-family-block', 'Social', 'Spend attention on people, not just messages', 'Do a caring act', 'Help, encourage, follow up, remember something important, or do a small act of care for someone close.', 'hand-heart', 3, true, 630),
  ('social-community-block', 'Social', 'Spend attention on people, not just messages', 'Join or plan something social', 'Look for an event, make a plan, join a group, or create a reason to be around people on purpose.', 'send', 1, true, 640),
  ('recovery-rest-block', 'Recovery', 'Protect energy and make the day lighter', 'Take a real rest block', 'Nap, sit quietly, lie down, breathe, or do nothing productive long enough for your nervous system to settle.', 'moon', 3, true, 710),
  ('recovery-mindful-block', 'Recovery', 'Protect energy and make the day lighter', 'Do a mindful reset', 'Meditate, body scan, breathe, journal softly, pray, or sit without inputs until your mind feels less crowded.', 'flower-2', 3, true, 720),
  ('recovery-entertainment-block', 'Recovery', 'Protect energy and make the day lighter', 'Enjoy something fully', 'Watch, read, or listen for pleasure without splitting attention across five other things.', 'disc-3', 3, true, 730),
  ('recovery-play-block', 'Recovery', 'Protect energy and make the day lighter', 'Enjoy low-stakes play', 'Choose a game, puzzle, playful experiment, or recreational activity where the point is decompression rather than fitness, output, or social duty.', 'gamepad-2', 3, true, 740),
  ('recovery-offline-block', 'Recovery', 'Protect energy and make the day lighter', 'Go offline for a while', 'Spend time away from feeds, chats, and input so your attention has room to come back.', 'eye', 2, true, 750),
  ('adventure-place-block', 'Adventure', 'Leave the default routine for a while', 'Go somewhere different', 'Visit a cafe, shop, street, event, library, neighborhood, or urban place that changes the texture of the day.', 'route', 2, true, 810),
  ('adventure-driving-block', 'Adventure', 'Leave the default routine for a while', 'Practice getting around', 'Drive, ride, park, navigate, or study routes in a way that builds confidence outside your usual radius.', 'car-front', 1, true, 820),
  ('adventure-nature-block', 'Adventure', 'Leave the default routine for a while', 'Visit an outdoor place', 'Go to a park, waterfront, viewpoint, garden, trail, or open-air place mainly for novelty and setting, not as a workout.', 'leaf', 3, true, 830),
  ('health-care-block', 'Health', 'Care for the body that carries the rest', 'Take care of your health', 'Handle hydration, supplements, posture, hygiene, symptoms, appointments, or anything your body has been asking for.', 'heart-pulse', 3, true, 910),
  ('health-sleep-block', 'Health', 'Care for the body that carries the rest', 'Support tonight''s sleep', 'Set a bedtime, reduce stimulation, manage caffeine, dim screens, cool the room, or wind down early enough to improve sleep.', 'clock-check', 2, true, 920)
ON CONFLICT ("slug") DO UPDATE SET
  "category" = EXCLUDED."category",
  "category_description" = EXCLUDED."category_description",
  "name" = EXCLUDED."name",
  "detail" = EXCLUDED."detail",
  "icon" = EXCLUDED."icon",
  "enabled" = EXCLUDED."enabled",
  "sort_order" = EXCLUDED."sort_order",
  "updated_at" = now();
