UPDATE story SET pains = '["Proses registrasi terlalu panjang", "Harus verifikasi email dan NIM", "Lupa password sering terjadi"]'::jsonb, gains = '["Onboarding cepat, langsung bisa akses", "Single sign-on dengan akun kampus"]'::jsonb WHERE code = 'S1' AND activity_id IN (SELECT id FROM activity WHERE project_id = 3);
UPDATE story SET pains = '["Keyword tidak ditemukan", "Hasil pencarian tidak relevan", "Filter lomba terlalu sedikit"]'::jsonb, gains = '["Ditemukan karya yang relevan", "Bisa filter berdasarkan lomba dan tahun", "Rekomendasi karya serupa"]'::jsonb WHERE code = 'S2' AND activity_id IN (SELECT id FROM activity WHERE project_id = 3);
UPDATE story SET pains = '["Tidak bisa lihat isi dokumen", "Loading preview terlalu lama", "Watermark mengganggu bacaan"]'::jsonb, gains = '["Bisa lihat 3-5 slide pertama", "Preview cepat dan ringan", "Informasi metadata lengkap"]'::jsonb WHERE code = 'S3' AND activity_id IN (SELECT id FROM activity WHERE project_id = 3);
UPDATE story SET pains = '["Upload gagal tanpa error", "Format file tidak didukung", "Batas ukuran file terlalu kecil"]'::jsonb, gains = '["Upload berhasil dengan perlindungan", "Auto-watermark langsung aktif", "Bisa atur visibilitas publik/privat"]'::jsonb WHERE code = 'S4' AND activity_id IN (SELECT id FROM activity WHERE project_id = 3);
UPDATE story SET pains = '["Anggota tim tidak teridentifikasi", "Sulit koordinasi persetujuan tim", "Tidak tahu siapa yang sudah approve"]'::jsonb, gains = '["Semua anggota terasosiasi", "Notifikasi otomatis ke anggota", "Status persetujuan transparan"]'::jsonb WHERE code = 'S5' AND activity_id IN (SELECT id FROM activity WHERE project_id = 3);
UPDATE story SET pains = '["Tidak ada kontrol akses", "Tidak tahu siapa yang lihat karya", "Akses bocor ke pihak tidak diinginkan"]'::jsonb, gains = '["Kontrol penuh, bisa cabut akses", "Log akses tercatat", "Bisa set expiry waktu akses"]'::jsonb WHERE code = 'S6' AND activity_id IN (SELECT id FROM activity WHERE project_id = 3);
UPDATE story SET pains = '["Tidak ada kontak kreator", "Chat lewat DM Instagram tidak profesional", "Pesan sering tidak dibalas"]'::jsonb, gains = '["Kontak langsung via WhatsApp", "Template pesan otomatis tersedia", "Respons lebih cepat dan profesional"]'::jsonb WHERE code = 'S7' AND activity_id IN (SELECT id FROM activity WHERE project_id = 3);
UPDATE story SET pains = '["Prestasi tidak terdokumentasi", "Portofolio tersebar di banyak tempat", "Tidak ada halaman publik yang rapi"]'::jsonb, gains = '["Profil profesional", "Semua karya terkumpul di satu halaman", "Bisa dibagikan ke rekruter"]'::jsonb WHERE code = 'S8' AND activity_id IN (SELECT id FROM activity WHERE project_id = 3);
UPDATE story SET pains = '["Tidak ada cara apresiasi", "Kreator tidak tahu karyanya diminati", "Tidak ada feedback dari pembaca"]'::jsonb, gains = '["Apresiasi ke kreator", "Kreator termotivasi berbagi lebih", "Bisa lihat karya populer"]'::jsonb WHERE code = 'S9' AND activity_id IN (SELECT id FROM activity WHERE project_id = 3);
